Ab/pull open data
mitodl/ol-data-pipelines pull request #20
Opened 2021-02-03 22:21 UTC by abeglova

2021-02-05 17:28 UTC, blarghmatey requested changes

2021-02-05 17:28 UTC, blarghmatey commented on src/ol_data_pipelines/open_discussions/solids.py
> +def download_postgres_data(context: SolidExecutionContext, query: String):
I think that `download` is a bit of a misnomer. I also think that encoding information about an implementation detail of the systems isn't necessary. We should aim to have the solid definitions be descriptive of _what_ is happening, rather then _where_ it's happening. We should probably also establish a controlled vocabulary for our pipelines to avoid any ambiguity, but for now perhaps `transfer_courserun_ids` or `extract` or `fetch`.

2021-02-05 17:28 UTC, blarghmatey commented on src/ol_data_pipelines/open_discussions/solids.py
> +    yield Output(output_resource.output_folder, "query_folder")
If the purpose of creating the class object for the Parquet output is to maintain a reference to the output attribute, perhaps we should create a standard [Pydantic](https://pydantic-docs.helpmanual.io/) model that we store as a `lib` which we can hydrate with that information and which we can attach validation logic to.

2021-02-10 16:08 UTC, blarghmatey commented on src/ol_data_pipelines/lib/parquet_file_rendering.py
> +        if clear_existing_files:
So, given that we are writing the data out as S3 there isn't any option for find/replace/update rows as the unit of work is at the level of a Parquet file. Since the tables are small, we should probably be writing them out as a single Parquet file, so if we simply write out the data it will automatically overwrite the data that is available in S3.

2021-02-10 16:13 UTC, blarghmatey commented on src/ol_data_pipelines/open_discussions/solids.py
> +    yield Output(output_resource.output_folder, "query_folder")
My previous comment was about the prior implementation of the parquet "resource", not about the output being produced.

That being said, if there is no meaningful output for a given solid then the supported pattern is to yield an `Output` of type `dagster.Nothing` https://docs.dagster.io/_apidocs/types

2021-02-10 18:12 UTC, abeglova commented on src/ol_data_pipelines/lib/parquet_file_rendering.py
> +        if clear_existing_files:
There are currently 123,054 users on production, which can definitely be one file. RC has 97352 and I had no problem querying for all of them at once but probably better not to in production. I'll replace `stream_parquet_files`  function to query in chunks than writes everything in one file

2021-02-10 20:28 UTC, blarghmatey approved these changes

2021-02-10 20:28 UTC, blarghmatey commented
I think this looks good for an initial pass. :+1:

2021-02-10 20:37 UTC, merged